import type { Question } from '@/lib/quiz/types';

const examId = 'claude-api';

export const claudeApi: Question[] = [
  {
    id: 'api-01',
    examId,
    domain: 'basics',
    type: 'multi',
    question: 'Messages API（POST /v1/messages）のリクエストで必須のパラメータをすべて選べ。',
    choices: ['model', 'max_tokens', 'messages', 'system', 'temperature'],
    answer: [0, 1, 2],
    explanation: 'model・max_tokens・messages が必須です。system や temperature は任意のパラメータです。',
  },
  {
    id: 'api-02',
    examId,
    domain: 'basics',
    type: 'single',
    question: 'Claude API で、利用する API のバージョンを指定する HTTP ヘッダーはどれか。',
    choices: ['anthropic-version', 'x-api-version', 'claude-version', 'accept-version'],
    answer: [0],
    explanation: 'リクエストには認証用の x-api-key と、API バージョンを指定する anthropic-version ヘッダーを付けます（公式 SDK は自動で付与します）。',
  },
  {
    id: 'api-03',
    examId,
    domain: 'basics',
    type: 'single',
    question: 'Messages API でシステムプロンプトを指定する正しい方法はどれか。',
    choices: [
      'リクエストのトップレベルの system パラメータに指定する',
      'messages 配列に role: "system" のメッセージを入れる',
      'HTTP ヘッダー x-system-prompt に入れる',
      '最初の assistant メッセージに書く',
    ],
    answer: [0],
    explanation: 'Messages API では、システムプロンプトは messages ではなくトップレベルの system パラメータで渡します。messages の role は user と assistant です。',
  },
  {
    id: 'api-04',
    examId,
    domain: 'basics',
    type: 'single',
    question: 'レスポンスの文章が途中で切れていた。stop_reason の値として最も可能性が高いものはどれか。',
    choices: ['"max_tokens"', '"end_turn"', '"tool_use"', '"stop_sequence"'],
    answer: [0],
    explanation: 'max_tokens に達して生成が打ち切られると stop_reason は "max_tokens" になります。自然に回答を終えた場合は "end_turn" です。',
  },
  {
    id: 'api-05',
    examId,
    domain: 'basics',
    type: 'single',
    question: 'stream: true を指定したとき、レスポンスはどの形式で返るか。',
    choices: ['Server-Sent Events（SSE）のイベントストリーム', 'WebSocket のメッセージ', '1 つの巨大な JSON', 'gzip 圧縮された CSV'],
    answer: [0],
    explanation: 'ストリーミングは SSE で返り、message_start、content_block_delta、message_stop などのイベントが順に届きます。',
  },
  {
    id: 'api-06',
    examId,
    domain: 'basics',
    type: 'single',
    question: 'API から HTTP 429 エラーが返ってきた。適切な対応はどれか。',
    choices: [
      'レート制限に達しているので、待機時間を伸ばしながら（指数バックオフで）再試行する',
      'API キーが無効なので、すぐに新しいキーを発行する',
      'リクエストの JSON 形式が誤っているので修正する',
      'モデル名が存在しないので変更する',
    ],
    answer: [0],
    explanation: '429 はレート制限を表します。retry-after ヘッダーなどを参考に、バックオフしながら再試行します。認証エラーは 401、形式エラーは 400 です。',
  },
  {
    id: 'api-07',
    examId,
    domain: 'tools',
    type: 'single',
    question: 'ツール定義で、ツールが受け取る引数の形を指定するフィールドはどれか。',
    choices: ['input_schema（JSON Schema）', 'parameters_xml', 'arguments', 'signature'],
    answer: [0],
    explanation: 'ツールは name・description・input_schema で定義します。input_schema には引数の型や必須項目を JSON Schema で書きます。',
  },
  {
    id: 'api-08',
    examId,
    domain: 'tools',
    type: 'single',
    question: 'Claude が tool_use ブロックを返した。ツールを実行した結果を Claude に返す正しい方法はどれか。',
    choices: [
      '次の user メッセージに、tool_use_id を指定した tool_result ブロックを入れて送る',
      '次の assistant メッセージに結果のテキストを入れて送る',
      'system パラメータに結果を追記する',
      '新しい会話を始めて結果だけを送る',
    ],
    answer: [0],
    explanation: 'ツールの結果は user ロールのメッセージに tool_result ブロックとして入れ、対応する tool_use の id を tool_use_id に指定します。',
  },
  {
    id: 'api-09',
    examId,
    domain: 'tools',
    type: 'single',
    question: 'ツールの description を書くときのベストプラクティスとして最も適切なものはどれか。',
    choices: [
      '何をするツールか、いつ使うべきか、各引数の意味や制約を具体的に書く',
      'できるだけ短く 1 単語で書く',
      'description は空にして名前だけで判断させる',
      '実装のソースコードをそのまま貼る',
    ],
    answer: [0],
    explanation: 'Claude はツールの説明を読んで、使うかどうかと引数の値を決めます。用途・使う場面・引数の意味や制約を具体的に書くほど、適切に使われやすくなります。',
  },
  {
    id: 'api-10',
    examId,
    domain: 'perf',
    type: 'single',
    question: '毎回同じ長いシステムプロンプト（マニュアル全文）を送っている。コストとレイテンシを下げるために使う機能はどれか。',
    choices: [
      'プロンプトキャッシュ（cache_control: {"type": "ephemeral"} を付ける）',
      'temperature を下げる',
      'max_tokens を増やす',
      'stream を false にする',
    ],
    answer: [0],
    explanation: '繰り返し使う長い先頭部分に cache_control を付けると、その部分がキャッシュされます。キャッシュからの読み込みは通常の入力トークンより安く、処理も速くなります。',
  },
  {
    id: 'api-11',
    examId,
    domain: 'perf',
    type: 'single',
    question: 'リアルタイム性は不要で、数万件の文書を要約したい。コストを最も抑えられる方法はどれか。',
    choices: ['Message Batches API で非同期にまとめて処理する', '並列数を最大にして通常の API を呼ぶ', 'ストリーミングで 1 件ずつ処理する', 'max_tokens を最大値にする'],
    answer: [0],
    explanation: 'Message Batches API は大量のリクエストを非同期で処理し、通常料金より割安（50% オフ）になります。結果はバッチ完了後にまとめて取得します。',
  },
  {
    id: 'api-12',
    examId,
    domain: 'perf',
    type: 'single',
    question: '送信前に、リクエストが何トークンになるかを正確に知りたい。使う API はどれか。',
    choices: ['Token Counting API（/v1/messages/count_tokens）', '文字数を 4 で割る', 'Models API', 'Batches API'],
    answer: [0],
    explanation: 'count_tokens エンドポイントに、送る予定の messages・system・tools などを渡すと、入力トークン数を返します。文字数からの概算は日本語では特にずれが大きくなります。',
  },
  {
    id: 'api-13',
    examId,
    domain: 'basics',
    type: 'single',
    question: 'Messages API で画像を入力する方法として正しいものはどれか。',
    choices: [
      'content に type: "image" のブロックを入れ、source に base64 データや URL を指定する',
      '画像を別のエンドポイントにアップロードしないと使えない',
      '画像のファイル名をテキストで送れば自動で読み込まれる',
      'system パラメータに画像のバイナリを入れる',
    ],
    answer: [0],
    explanation: 'user メッセージの content に image ブロックを含めます。source には base64 エンコードしたデータ（media_type 付き）や URL などを指定できます。',
  },
  {
    id: 'api-14',
    examId,
    domain: 'advanced',
    type: 'single',
    question: 'Claude 4.7 以降のモデルで、Claude にどのくらい深く考えさせるかを調整したい。推奨される方法はどれか。',
    choices: [
      'thinking: {"type": "adaptive"} を指定し、output_config の effort で深さを調整する',
      'thinking: {"type": "enabled", "budget_tokens": 10000} で思考の予算を指定する',
      'temperature を 0 にする',
      'max_tokens をできるだけ小さくする',
    ],
    answer: [0],
    explanation: '最新のモデルでは adaptive thinking を使い、effort で思考の深さを調整します。budget_tokens で予算を指定する従来の方式（type: "enabled"）は、Claude 4.6 では非推奨、Claude 4.7 以降では 400 エラーになります。',
  },
];
