import type { Question } from '@/lib/quiz/types';

const examId = 'databricks-ml-associate';

export const databricksMl: Question[] = [
  {
    id: 'mla-01',
    examId,
    domain: 'mlflow',
    type: 'single',
    question: 'MLflow で、学習率などのハイパーパラメータを実行（run）に記録する関数はどれか。',
    choices: ['mlflow.log_param', 'mlflow.log_metric', 'mlflow.log_artifact', 'mlflow.set_tag'],
    answer: [0],
    explanation: 'ハイパーパラメータは log_param、精度や損失などの数値結果は log_metric、ファイルは log_artifact で記録するのが基本です。',
  },
  {
    id: 'mla-02',
    examId,
    domain: 'mlflow',
    type: 'single',
    question: 'scikit-learn の学習コードをほとんど変えずに、パラメータ・メトリクス・モデルを自動で記録したい。最も簡単な方法はどれか。',
    choices: ['mlflow.autolog() を呼ぶ', 'すべての値を print して保存する', 'モデルを pickle で DBFS に保存する', 'mlflow.log_metric を学習ループの外で 1 回だけ呼ぶ'],
    answer: [0],
    explanation: 'mlflow.autolog() は、対応ライブラリの学習呼び出しをフックして、パラメータ・メトリクス・モデルを自動的に記録します。',
  },
  {
    id: 'mla-03',
    examId,
    domain: 'mlflow',
    type: 'single',
    question: 'Unity Catalog のモデルレジストリで、本番で使うモデルバージョンを指し示す推奨の方法はどれか。',
    choices: [
      'エイリアス（例: champion）をバージョンに付与し、推論側はエイリアスでモデルを読み込む',
      'ステージを Production に遷移させる',
      'モデル名の末尾に _prod を付けて別モデルとして登録する',
      'バージョン番号を推論コードにハードコードする',
    ],
    answer: [0],
    explanation: 'Unity Catalog のモデルではステージの代わりにエイリアスを使います。推論側が models:/catalog.schema.model@champion のように参照すれば、エイリアスの付け替えだけでモデルを切り替えられます。',
  },
  {
    id: 'mla-04',
    examId,
    domain: 'modeling',
    type: 'single',
    question: '次のうち、データリーケージ（情報漏えい）を引き起こしている手順はどれか。',
    choices: [
      'データ全体で StandardScaler を fit してから、学習用と評価用に分割した',
      '学習用データだけで StandardScaler を fit し、評価用データには transform だけを適用した',
      '学習前にランダムシードを固定した',
      '評価用データを学習に一切使わなかった',
    ],
    answer: [0],
    explanation: '分割前に全データでスケーラーを fit すると、評価用データの統計情報が学習側に漏れ、評価が楽観的になります。前処理は学習データだけで fit するのが原則です。',
  },
  {
    id: 'mla-05',
    examId,
    domain: 'modeling',
    type: 'single',
    question: '不正取引が全体の 1% しかない分類問題で、モデルの評価指標として正解率（accuracy）だけに頼るべきでない理由はどれか。',
    choices: [
      '常に「不正ではない」と予測するだけで約 99% の正解率になり、不正を検出できているか分からないため',
      '正解率は回帰問題にしか使えないため',
      '正解率は計算コストが高いため',
      '不均衡データでは正解率を計算できないため',
    ],
    answer: [0],
    explanation: 'クラスが大きく偏っていると、少数クラスを無視しても正解率は高くなります。適合率・再現率・F1 や PR 曲線など、少数クラスの検出性能を見られる指標を併用します。',
  },
  {
    id: 'mla-06',
    examId,
    domain: 'modeling',
    type: 'single',
    question: '学習データでの精度が 99%、検証データでの精度が 70% だった。最も可能性が高い状態はどれか。',
    choices: ['過学習（オーバーフィッティング）', '学習不足（アンダーフィッティング）', 'データリーケージがまったくない理想的な状態', '学習率が小さすぎて学習が進んでいない'],
    answer: [0],
    explanation: '学習データでは非常に良く、未知データでは大きく悪化するのは過学習の典型です。正則化、モデルの単純化、データの追加などで対処します。',
  },
  {
    id: 'mla-07',
    examId,
    domain: 'modeling',
    type: 'single',
    question: 'Spark ML で、複数のステージ（特徴量変換と推定器）からなる Pipeline に対して fit() を呼ぶと何が返るか。',
    choices: ['PipelineModel（transform できるモデル）', '予測結果の DataFrame', '学習済みの重みの配列', 'None'],
    answer: [0],
    explanation: 'Pipeline は Estimator で、fit() の結果は Transformer である PipelineModel になります。PipelineModel.transform(df) で予測列を追加できます。',
  },
  {
    id: 'mla-08',
    examId,
    domain: 'modeling',
    type: 'single',
    question: 'Databricks AutoML の特徴として正しいものはどれか。',
    choices: [
      '各試行のソースコードを含むノートブックを生成し、利用者が中身を確認・編集できる',
      '生成されたモデルの中身は確認できないブラックボックスになる',
      'GPU クラスタでしか実行できない',
      '分類問題には使えない',
    ],
    answer: [0],
    explanation: 'Databricks AutoML は試行ごとに再現可能なノートブックを生成します。最良モデルのコードをベースに手作業で改良する、という「ガラスボックス」型の使い方ができます。',
  },
  {
    id: 'mla-09',
    examId,
    domain: 'features',
    type: 'single',
    question: '時系列データの特徴量を学習データに結合するとき、予測時点より未来の特徴量値が混入しないようにしたい。最も適切な方法はどれか。',
    choices: [
      'タイムスタンプキーを持つ特徴量テーブルで、ポイントインタイム結合を使う',
      '特徴量テーブルの最新値をすべての行に結合する',
      '学習データをランダムにシャッフルしてから結合する',
      '特徴量を毎回手計算して CSV で渡す',
    ],
    answer: [0],
    explanation: 'ポイントインタイム結合では、各学習行のタイムスタンプ時点で有効だった特徴量値だけを使うため、未来情報の混入（リーケージ）を防げます。',
  },
  {
    id: 'mla-10',
    examId,
    domain: 'features',
    type: 'single',
    question: 'カテゴリ数が 3 つの名義尺度の特徴量（例: 赤・青・緑）を線形モデルに入力したい。一般的な前処理はどれか。',
    choices: ['ワンホットエンコーディング', '赤=1、青=2、緑=3 の整数に置き換えてそのまま使う', '列を削除する', '平均値で補完する'],
    answer: [0],
    explanation: '名義尺度を単純な整数に置き換えると、存在しない大小関係をモデルが学習してしまいます。ワンホットエンコーディングで各カテゴリを独立した列にするのが一般的です。',
  },
  {
    id: 'mla-11',
    examId,
    domain: 'deploy',
    type: 'single',
    question: '数億行ある Delta テーブルに対し、登録済みの MLflow モデルで夜間にまとめて予測したい。最も適切な方法はどれか。',
    choices: [
      'mlflow.pyfunc.spark_udf でモデルを UDF 化し、Spark で分散推論する',
      'リアルタイムのサービングエンドポイントに 1 行ずつ REST リクエストを送る',
      'ドライバーに全データを toPandas() で集めて predict する',
      'ノートブックで手動で 1 行ずつ予測する',
    ],
    answer: [0],
    explanation: '大規模なバッチ推論では、spark_udf でモデルを Spark に載せて分散実行するのが定石です。リアルタイムエンドポイントは低レイテンシの個別リクエスト向けです。',
  },
  {
    id: 'mla-12',
    examId,
    domain: 'deploy',
    type: 'single',
    question: 'Web アプリから個々のリクエストに対して低レイテンシで予測結果を返したい。Databricks で最も適した手段はどれか。',
    choices: ['Model Serving のエンドポイント（REST API）', '毎晩のバッチジョブ', 'Databricks SQL のアラート', 'Delta テーブルへの書き込み'],
    answer: [0],
    explanation: 'Model Serving はモデルを REST API として公開し、オートスケールしながら低レイテンシで推論を返します。',
  },
];
