import type { Question } from '@/lib/quiz/types';

const examId = 'databricks-data-engineer-associate';

export const databricksDataEngineer: Question[] = [
  {
    id: 'dea-01',
    examId,
    domain: 'delta',
    type: 'single',
    question: '誤った UPDATE を実行してしまった Delta テーブル sales を、バージョン 5 の状態に戻したい。正しいコマンドはどれか。',
    choices: [
      'RESTORE TABLE sales TO VERSION AS OF 5',
      'ROLLBACK TABLE sales TO VERSION 5',
      'UNDO TABLE sales VERSION 5',
      'ALTER TABLE sales SET VERSION = 5',
    ],
    answer: [0],
    explanation: 'Delta Lake では RESTORE TABLE ... TO VERSION AS OF（または TIMESTAMP AS OF）でテーブルを過去の状態に戻せます。復元操作自体も新しいバージョンとして履歴に記録されます。',
  },
  {
    id: 'dea-02',
    examId,
    domain: 'delta',
    type: 'single',
    question: 'Delta テーブルに対してデフォルトの保持期間で VACUUM を実行した。起こりうることとして最も適切なものはどれか。',
    choices: [
      '保持期間より古く、現在のバージョンから参照されないデータファイルが削除され、それらを必要とする過去バージョンへのタイムトラベルができなくなる',
      'トランザクションログがすべて削除され、DESCRIBE HISTORY が空になる',
      '小さなファイルが結合され、クエリ性能が向上する',
      'テーブルのすべての過去バージョンが即座に削除される',
    ],
    answer: [0],
    explanation: 'VACUUM は、現在のテーブル状態から参照されず保持期間（デフォルト 7 日）を過ぎたデータファイルを削除します。そのファイルを必要とする古いバージョンにはタイムトラベルできなくなります。ファイルの結合は OPTIMIZE の役割です。',
  },
  {
    id: 'dea-03',
    examId,
    domain: 'delta',
    type: 'single',
    question: 'ストリーミング取り込みにより小さなファイルが大量にでき、読み取りが遅くなっている。まず実行すべき操作はどれか。',
    choices: ['OPTIMIZE', 'VACUUM', 'REFRESH TABLE', 'ANALYZE TABLE ... COMPUTE STATISTICS'],
    answer: [0],
    explanation: 'OPTIMIZE は小さなファイルを大きなファイルにまとめ（コンパクション）、スモールファイル問題を解消します。VACUUM は不要ファイルの削除で、ファイルサイズは改善しません。',
  },
  {
    id: 'dea-04',
    examId,
    domain: 'delta',
    type: 'single',
    question: '顧客マスタの変更データ（新規・更新）を、既存の Delta テーブル customers に反映（アップサート）したい。最も適切な SQL はどれか。',
    choices: [
      'MERGE INTO customers USING updates ON customers.id = updates.id WHEN MATCHED THEN UPDATE SET * WHEN NOT MATCHED THEN INSERT *',
      'INSERT OVERWRITE customers SELECT * FROM updates',
      'INSERT INTO customers SELECT * FROM updates',
      'UPDATE customers SET * FROM updates',
    ],
    answer: [0],
    explanation: 'MERGE INTO は一致する行の更新と一致しない行の挿入を 1 つのアトミックな操作で行えます。INSERT INTO は重複を生み、INSERT OVERWRITE は既存データを置き換えてしまいます。',
  },
  {
    id: 'dea-05',
    examId,
    domain: 'ingest',
    type: 'single',
    question: 'クラウドストレージに継続的に届く JSON ファイルを、新しいファイルだけ増分で取り込みたい。スキーマの推論と変化への追従も行いたい。最適な方法はどれか。',
    choices: [
      'Auto Loader（spark.readStream.format("cloudFiles")）',
      '毎回 spark.read.json() でディレクトリ全体を読み込む',
      'CREATE TABLE ... AS SELECT を毎時実行する',
      'dbutils.fs.cp でファイルを DBFS にコピーする',
    ],
    answer: [0],
    explanation: 'Auto Loader（cloudFiles ソース）は処理済みファイルをチェックポイントで管理し、新規ファイルだけを効率的に取り込みます。スキーマ推論やスキーマ進化にも対応しています。',
  },
  {
    id: 'dea-06',
    examId,
    domain: 'ingest',
    type: 'multi',
    question: 'COPY INTO について正しい説明をすべて選べ。',
    choices: [
      '同じコマンドを再実行しても、読み込み済みのファイルはスキップされる（冪等）',
      'SQL コマンドとして実行できる',
      'Structured Streaming のチェックポイントの場所を必ず指定する必要がある',
      '読み込みが終わったソースファイルは自動的に削除される',
    ],
    answer: [0, 1],
    explanation: 'COPY INTO はロード済みファイルを記録しているので、再実行しても同じファイルを二重に取り込みません。ソースファイルは削除されず、ストリーミングのチェックポイント指定も不要です。',
  },
  {
    id: 'dea-07',
    examId,
    domain: 'pipeline',
    type: 'single',
    question: 'メダリオンアーキテクチャで、重複の除去・型の整形・不正値のクレンジングを主に行うレイヤーはどれか。',
    choices: ['Silver', 'Bronze', 'Gold', 'Platinum'],
    answer: [0],
    explanation: 'Bronze は生データをそのまま保持し、Silver でクレンジング・重複除去・結合などを行い、Gold でビジネス向けの集計を作るのが一般的な役割分担です。',
  },
  {
    id: 'dea-08',
    examId,
    domain: 'pipeline',
    type: 'single',
    question: '宣言型パイプライン（Lakeflow Declarative Pipelines、旧 Delta Live Tables）で、id が NULL のレコードも残したまま違反件数だけを記録したい。どのエクスペクテーションが適切か。',
    choices: [
      'CONSTRAINT valid_id EXPECT (id IS NOT NULL)',
      'CONSTRAINT valid_id EXPECT (id IS NOT NULL) ON VIOLATION DROP ROW',
      'CONSTRAINT valid_id EXPECT (id IS NOT NULL) ON VIOLATION FAIL UPDATE',
      'CONSTRAINT valid_id CHECK (id IS NOT NULL)',
    ],
    answer: [0],
    explanation: 'ON VIOLATION を指定しないエクスペクテーションは、違反レコードもターゲットに書き込み、違反件数をメトリクスとして記録します。DROP ROW は違反行を捨て、FAIL UPDATE はパイプラインの更新を失敗させます。',
  },
  {
    id: 'dea-09',
    examId,
    domain: 'pipeline',
    type: 'single',
    question: 'ストリーミングのクエリを、その時点で利用可能なデータをすべて処理したら停止する「増分バッチ」として 1 日 1 回実行したい。適切なトリガーはどれか。',
    choices: [
      'trigger(availableNow=True)',
      'trigger(processingTime="1 day")',
      'trigger(continuous="1 day")',
      'トリガーを指定しない',
    ],
    answer: [0],
    explanation: 'availableNow トリガーは、起動時点で利用可能なデータを（複数のマイクロバッチに分けて）すべて処理してから停止します。ジョブで定期実行すれば、ストリーミングの増分処理をバッチのように運用できます。',
  },
  {
    id: 'dea-10',
    examId,
    domain: 'ops',
    type: 'single',
    question: '5 つのタスクからなるジョブで、4 番目のタスクだけが失敗した。成功済みのタスクを再実行せずに、失敗したタスクとその下流だけを実行し直したい。どの機能を使うか。',
    choices: ['実行の修復（Repair run）', 'ジョブのクローン', '「今すぐ実行」で全体を再実行', 'タスクの無効化'],
    answer: [0],
    explanation: 'Repair run を使うと、失敗したタスクと、それに依存するタスクだけを再実行できます。成功済みタスクの再計算を避けられるので時間とコストを節約できます。',
  },
  {
    id: 'dea-11',
    examId,
    domain: 'governance',
    type: 'single',
    question: 'アナリストのグループに main.sales.orders の SELECT 権限を付与したが、クエリするとアクセスエラーになる。不足している可能性が最も高い権限はどれか。',
    choices: [
      'カタログ main の USE CATALOG と、スキーマ sales の USE SCHEMA',
      'テーブルの MODIFY',
      'メタストアの CREATE CATALOG',
      'クラスタの CAN MANAGE',
    ],
    answer: [0],
    explanation: 'Unity Catalog では、テーブルを読むには SELECT に加えて、親オブジェクトに対する USE CATALOG と USE SCHEMA が必要です。',
  },
  {
    id: 'dea-12',
    examId,
    domain: 'governance',
    type: 'single',
    question: '外部テーブル（external table）に対して DROP TABLE を実行したときの動作として正しいものはどれか。',
    choices: [
      'テーブルのメタデータが削除され、外部ロケーション上のデータファイルは残る',
      'メタデータとデータファイルの両方が即座に削除される',
      'データファイルが削除され、メタデータは残る',
      '外部テーブルは DROP できない',
    ],
    answer: [0],
    explanation: '外部テーブルのデータの管理責任は利用者側にあるため、DROP TABLE で削除されるのはメタデータだけです。マネージドテーブルでは、データファイルも Databricks の管理下で削除されます。',
  },
  {
    id: 'dea-13',
    examId,
    domain: 'governance',
    type: 'single',
    question: 'Unity Catalog でテーブルを完全修飾名で参照するときの正しい形式はどれか。',
    choices: ['catalog.schema.table', 'schema.catalog.table', 'workspace.database.table', 'metastore.table'],
    answer: [0],
    explanation: 'Unity Catalog は「カタログ.スキーマ.テーブル」の 3 階層の名前空間を使います（例: main.sales.orders）。',
  },
];
