import type { Question } from '@/lib/quiz/types';

const examId = 'databricks-data-analyst-associate';

export const databricksDataAnalyst: Question[] = [
  {
    id: 'daa-01',
    examId,
    domain: 'dbsql',
    type: 'single',
    question: 'Databricks SQL のクエリエディタやダッシュボードでクエリを実行するために必要なコンピュートはどれか。',
    choices: ['SQL ウェアハウス', 'モデルサービングエンドポイント', 'Vector Search エンドポイント', 'ジョブクラスタのみ'],
    answer: [0],
    explanation: 'Databricks SQL のクエリは SQL ウェアハウス上で実行されます。サーバーレス SQL ウェアハウスを使うと起動待ちが短く、管理の手間も減ります。',
  },
  {
    id: 'daa-02',
    examId,
    domain: 'dbsql',
    type: 'single',
    question: 'ビュー（CREATE VIEW）とテーブル（CREATE TABLE AS SELECT）の違いとして正しいものはどれか。',
    choices: [
      'ビューはクエリ定義だけを保存し、参照のたびに元テーブルから結果を計算する',
      'ビューは作成時点のデータのコピーを保存する',
      'CTAS で作ったテーブルは元テーブルの変更に自動で追従する',
      'ビューには権限を付与できない',
    ],
    answer: [0],
    explanation: 'ビューはクエリの定義だけを持ち、参照するたびに計算されます。CTAS は作成時点の結果をデータとして書き込むため、元テーブルの変更には追従しません。',
  },
  {
    id: 'daa-03',
    examId,
    domain: 'sql',
    type: 'single',
    question: '顧客ごとに最新の注文 1 件だけを取り出したい。サブクエリで使う式として最も適切なものはどれか。',
    code: 'SELECT * FROM (\n  SELECT *, /* ここ */ AS rn\n  FROM orders\n) WHERE rn = 1',
    choices: [
      'ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_ts DESC)',
      'RANK() OVER (ORDER BY order_ts DESC)',
      'COUNT(*) OVER (PARTITION BY customer_id)',
      'MAX(order_ts) OVER ()',
    ],
    answer: [0],
    explanation: '顧客ごとにパーティションを切り、注文日時の降順で ROW_NUMBER を振れば、rn = 1 が各顧客の最新注文になります。RANK を PARTITION なしで使うと全体の順位になってしまいます。',
  },
  {
    id: 'daa-04',
    examId,
    domain: 'sql',
    type: 'single',
    question: 'email 列に NULL を含むテーブルで、COUNT(*) と COUNT(email) の結果について正しいものはどれか。',
    choices: [
      'COUNT(email) は email が NULL の行を数えないため、COUNT(*) 以下の値になる',
      'どちらも常に同じ値になる',
      'COUNT(email) は NULL を 0 として数える',
      'COUNT(*) は NULL を含む行を数えない',
    ],
    answer: [0],
    explanation: 'COUNT(列) はその列が NULL でない行だけを数えます。COUNT(*) は NULL の有無に関係なくすべての行を数えます。',
  },
  {
    id: 'daa-05',
    examId,
    domain: 'sql',
    type: 'single',
    question: '配列型の列 tags を、要素ごとに 1 行ずつに展開したい。使う関数はどれか。',
    choices: ['explode', 'flatten', 'collect_list', 'array_join'],
    answer: [0],
    explanation: 'explode は配列（またはマップ）の各要素を別々の行に展開します。collect_list は逆に複数行を配列にまとめる集約関数です。',
  },
  {
    id: 'daa-06',
    examId,
    domain: 'sql',
    type: 'single',
    question: 'タイムスタンプ列 order_ts から月単位で売上を集計したい。GROUP BY に使う式として適切なものはどれか。',
    choices: ["date_trunc('MONTH', order_ts)", "date_add(order_ts, 30)", "datediff(order_ts, current_date())", "to_json(order_ts)"],
    answer: [0],
    explanation: "date_trunc('MONTH', ts) はタイムスタンプを月初に切り捨てるので、月ごとのグルーピングに使えます。",
  },
  {
    id: 'daa-07',
    examId,
    domain: 'sql',
    type: 'single',
    question: 'customers（全顧客）と orders を結合し、注文がない顧客も結果に残したい。正しい結合はどれか。',
    choices: [
      'customers LEFT JOIN orders ON customers.id = orders.customer_id',
      'customers INNER JOIN orders ON customers.id = orders.customer_id',
      'customers RIGHT JOIN orders ON customers.id = orders.customer_id',
      'customers CROSS JOIN orders',
    ],
    answer: [0],
    explanation: 'LEFT JOIN は左側（customers）のすべての行を残し、一致する注文がなければ orders 側の列が NULL になります。',
  },
  {
    id: 'daa-08',
    examId,
    domain: 'viz',
    type: 'single',
    question: '在庫数が閾値を下回ったら担当者に自動で通知したい。Databricks SQL の機能として最も適切なものはどれか。',
    choices: ['アラート（Alerts）', 'クエリスニペット', 'ビューの作成', 'クエリ履歴'],
    answer: [0],
    explanation: 'Databricks SQL のアラートは、クエリの結果を定期的に評価し、条件を満たしたときに通知先へ知らせます。',
  },
  {
    id: 'daa-09',
    examId,
    domain: 'viz',
    type: 'single',
    question: 'SQL を書かないビジネスユーザーが、自然言語でデータに質問して回答を得られるようにしたい。最も適した機能はどれか。',
    choices: ['AI/BI Genie スペース', 'SQL ウェアハウスの自動停止', 'Delta Sharing', 'クラスタポリシー'],
    answer: [0],
    explanation: 'AI/BI Genie では、対象テーブルや指示文を整えたスペースを用意しておくと、ユーザーが自然言語で質問して SQL ベースの回答を得られます。',
  },
  {
    id: 'daa-10',
    examId,
    domain: 'catalog',
    type: 'single',
    question: 'あるテーブルの列を変更する前に、その列に依存している下流のテーブルやダッシュボードを確認したい。最も適切な方法はどれか。',
    choices: [
      'Catalog Explorer で Unity Catalog のリネージを確認する',
      'クエリ履歴を 1 件ずつ目視で確認する',
      'DESCRIBE HISTORY を実行する',
      'SHOW GRANTS を実行する',
    ],
    answer: [0],
    explanation: 'Unity Catalog は、テーブルや列のリネージ（どこから来て、どこで使われているか）を自動で記録し、Catalog Explorer で確認できます。DESCRIBE HISTORY はテーブル自身の変更履歴です。',
  },
  {
    id: 'daa-11',
    examId,
    domain: 'catalog',
    type: 'single',
    question: 'Delta テーブルの書き込み履歴（いつ・誰が・どんな操作をしたか）を確認するコマンドはどれか。',
    choices: ['DESCRIBE HISTORY table_name', 'SHOW TABLES', 'DESCRIBE DETAIL table_name', 'SHOW COLUMNS IN table_name'],
    answer: [0],
    explanation: 'DESCRIBE HISTORY は、バージョンごとの操作内容・タイムスタンプ・実行ユーザーなどを返します。DESCRIBE DETAIL はファイル数やサイズなど現在の状態を返します。',
  },
  {
    id: 'daa-12',
    examId,
    domain: 'catalog',
    type: 'multi',
    question: 'マネージドテーブルと比べた、外部テーブルの特徴として正しいものをすべて選べ。',
    choices: [
      'データファイルの場所を利用者が指定する',
      'DROP TABLE してもデータファイルは削除されない',
      'Unity Catalog の権限管理の対象外になる',
      'SQL でクエリできない',
    ],
    answer: [0, 1],
    explanation: '外部テーブルは外部ロケーション上の指定パスにデータを置き、DROP してもファイルは残ります。Unity Catalog の権限管理の対象であり、通常どおり SQL でクエリできます。',
  },
];
