import type { VocabularyGroup } from '@/lib/quiz/types';

/**
 * Claude の頻出英単語。公式ドキュメントや出題範囲の説明で使われる用語と、
 * 英語の設問によく出る言い回しから選んだもの（実際の試験問題から集めたものではない）。
 */
export const CLAUDE_VOCABULARY: VocabularyGroup[] = [
  {
    id: 'phrasing',
    name: '設問の言い回し',
    words: [
      {
        en: 'address',
        pos: '動詞',
        ja: '（問題に）対処する',
        note: '名詞の「住所」ではなく、動詞で「（課題や懸念に）取り組む」という意味でよく使われます。',
        example: "Which approach best addresses the customer's concern about data privacy?",
        exampleJa: '顧客のデータプライバシーへの懸念に、最もよく対処できる方法はどれか。',
      },
      {
        en: 'mitigate',
        pos: '動詞',
        ja: '（悪影響を）軽減する',
        note: 'リスクを「なくす」のではなく「小さくする」という意味です。',
        example: 'Which measure would most effectively mitigate the risk of prompt injection?',
        exampleJa: 'プロンプトインジェクションのリスクを最も効果的に軽減する対策はどれか。',
      },
      {
        en: 'ensure',
        pos: '動詞',
        ja: '必ずそうなるようにする',
        example: 'How can the team ensure that every response follows the required JSON format?',
        exampleJa: 'すべての応答が必ず指定の JSON 形式に従うようにするには、チームはどうすればよいか。',
        avoid: ['verify'],
      },
      {
        en: 'leverage',
        pos: '動詞',
        ja: '活用する',
        note: '名詞では「てこ」ですが、設問では use とほぼ同じ意味で使われます。',
        example: 'The company wants to leverage its internal documents to answer employee questions.',
        exampleJa: 'その会社は、社内文書を活用して、社員の質問に答えたいと考えている。',
      },
      {
        en: 'prioritize',
        pos: '動詞',
        ja: '優先する',
        example: 'The customer prioritizes accuracy over response speed.',
        exampleJa: 'その顧客は、応答の速さよりも正確さを優先している。',
      },
      {
        en: 'constraint',
        pos: '名詞',
        ja: '制約',
        example: 'Given the budget constraint, which model is the most appropriate choice?',
        exampleJa: '予算の制約を踏まえると、最も適切なモデルはどれか。',
      },
      {
        en: 'requirement',
        pos: '名詞',
        ja: '要件',
        example: 'The application has a strict requirement to respond within two seconds.',
        exampleJa: 'このアプリケーションには、2 秒以内に応答するという厳しい要件がある。',
      },
      {
        en: 'trade-off',
        pos: '名詞',
        ja: '得失の兼ね合い',
        note: '一方をよくすると、もう一方が悪くなる関係のことです。',
        example: 'There is a trade-off between response quality and latency.',
        exampleJa: '応答の質と待ち時間のあいだには、兼ね合いがある。',
      },
      {
        en: 'stakeholder',
        pos: '名詞',
        ja: '利害関係者',
        example: 'Before the rollout, align with key stakeholders on the success criteria.',
        exampleJa: '展開の前に、主要な利害関係者と成功の基準をすり合わせておく。',
      },
      {
        en: 'outcome',
        pos: '名詞',
        ja: '結果・成果',
        example: 'Define measurable outcomes before starting the pilot.',
        exampleJa: '試験導入を始める前に、測定できる成果を決めておく。',
      },
      {
        en: 'feasible',
        pos: '形容詞',
        ja: '実現可能な',
        example: 'Is it feasible to process every incoming email in real time?',
        exampleJa: '届いたメールをすべてリアルタイムで処理することは、実現可能か。',
      },
      {
        en: 'appropriate',
        pos: '形容詞',
        ja: '適切な',
        example: 'Which of the following is the MOST appropriate next step?',
        exampleJa: '次のうち、最も適切な次の手順はどれか。',
      },
      {
        en: 'primary',
        pos: '形容詞',
        ja: '主な',
        note: '「最初の・初歩の」ではなく、「主な・いちばん重要な」の意味で使われることが多い語です。',
        example: 'What is the primary benefit of prompt caching?',
        exampleJa: 'プロンプトキャッシュの主な利点は何か。',
      },
      {
        en: 'subsequent',
        pos: '形容詞',
        ja: 'その後の',
        example: 'Subsequent requests that reuse the same prompt prefix can read from the cache.',
        exampleJa: '同じプロンプトの前半部分を使う、その後のリクエストは、キャッシュから読み込める。',
      },
      {
        en: 'regardless of',
        pos: '句',
        ja: '〜に関係なく',
        example: 'The system prompt applies regardless of which user sends the message.',
        exampleJa: 'システムプロンプトは、どのユーザーがメッセージを送るかに関係なく適用される。',
      },
    ],
  },
  {
    id: 'api',
    name: 'モデルと API',
    words: [
      {
        en: 'latency',
        pos: '名詞',
        ja: '応答までの待ち時間',
        note: '「遅延」とも訳します。throughput（処理量）と対で出てきます。',
        example: 'Streaming the response reduces the latency that users perceive.',
        exampleJa: '応答をストリーミングすると、ユーザーが感じる待ち時間が短くなる。',
      },
      {
        en: 'throughput',
        pos: '名詞',
        ja: '一定時間に処理できる量',
        example: 'To increase throughput, the team sends requests in parallel.',
        exampleJa: '処理量を増やすため、チームはリクエストを並列に送っている。',
      },
      {
        en: 'context window',
        pos: '名詞',
        ja: '一度に扱える情報量の上限',
        note: 'モデルが応答を作るときに参照できる文章の量の上限で、応答そのものも含みます。',
        example: 'Long conversations can eventually exceed the context window.',
        exampleJa: '長い会話は、いずれコンテキストウィンドウの上限を超えることがある。',
      },
      {
        en: 'rate limit',
        pos: '名詞',
        ja: '一定時間あたりの利用上限',
        example: 'When you exceed the rate limit, the API returns a 429 error.',
        exampleJa: '利用上限を超えると、API は 429 エラーを返す。',
      },
      {
        en: 'exponential backoff',
        pos: '名詞',
        ja: '再試行の間隔を倍々に延ばす方式',
        example: 'Retry failed requests using exponential backoff.',
        exampleJa: '失敗したリクエストは、間隔を倍々に延ばしながら再試行する。',
      },
      {
        en: 'payload',
        pos: '名詞',
        ja: '送受信するデータ本体',
        example: 'The request payload must include the model, max_tokens, and messages fields.',
        exampleJa: 'リクエストのデータ本体には、model・max_tokens・messages を含める必要がある。',
      },
      {
        en: 'schema',
        pos: '名詞',
        ja: 'データの構造の定義',
        example: 'Each tool needs a JSON schema that describes its input.',
        exampleJa: 'ツールごとに、入力の形を表す JSON スキーマが必要だ。',
      },
      {
        en: 'stop sequence',
        pos: '名詞',
        ja: '生成を止める合図の文字列',
        example: 'Generation stops when the model outputs a custom stop sequence.',
        exampleJa: 'モデルが指定の停止シーケンスを出力すると、生成が止まる。',
      },
      {
        en: 'cache hit',
        pos: '名詞',
        ja: 'キャッシュを再利用できたこと',
        example: 'A higher cache hit rate lowers both cost and latency.',
        exampleJa: 'キャッシュを再利用できる割合が高いほど、費用も待ち時間も下がる。',
      },
      {
        en: 'truncate',
        pos: '動詞',
        ja: '途中で切り詰める',
        example: 'The response was truncated because it reached the max_tokens limit.',
        exampleJa: 'max_tokens の上限に達したため、応答が途中で切れた。',
      },
      {
        en: 'deprecate',
        pos: '動詞',
        ja: '非推奨にする',
        note: '将来なくなる予定のため、使わないよう促すことです。名詞は deprecation です。',
        example: 'This parameter is deprecated and will be removed in a future version.',
        exampleJa: 'このパラメーターは非推奨で、将来の版で削除される。',
      },
      {
        en: 'deterministic',
        pos: '形容詞',
        ja: '同じ入力なら毎回同じ出力になる',
        note: '反対は non-deterministic です。モデルの出力は、同じ入力でも毎回同じとは限りません。',
        example: 'Model outputs are not fully deterministic, so tests should tolerate some variation.',
        exampleJa: 'モデルの出力は毎回同じとは限らないため、テストは多少の違いを許容するべきだ。',
        avoid: ['idempotent'],
      },
      {
        en: 'verbose',
        pos: '形容詞',
        ja: '冗長な',
        example: 'The answers are too verbose, so instruct the model to keep them short.',
        exampleJa: '回答が冗長すぎるので、短くまとめるようモデルに指示する。',
      },
      {
        en: 'concise',
        pos: '形容詞',
        ja: '簡潔な',
        example: 'Ask for a concise summary of no more than three sentences.',
        exampleJa: '3 文以内の簡潔な要約を求める。',
      },
      {
        en: 'multimodal',
        pos: '形容詞',
        ja: '文章や画像など複数の種類の情報を扱える',
        example: 'Because Claude is multimodal, it can analyze charts and screenshots as well as text.',
        exampleJa: 'Claude は文章だけでなく画像も扱えるため、グラフやスクリーンショットも分析できる。',
      },
    ],
  },
  {
    id: 'agents',
    name: 'エージェントとツール',
    words: [
      {
        en: 'orchestrate',
        pos: '動詞',
        ja: '全体を取りまとめて指揮する',
        example: 'A lead agent orchestrates several subagents that work in parallel.',
        exampleJa: '主となるエージェントが、並行して動く複数のサブエージェントを取りまとめる。',
      },
      {
        en: 'delegate',
        pos: '動詞',
        ja: '（仕事を）任せる',
        example: 'The main agent delegates code review to a specialized subagent.',
        exampleJa: 'メインのエージェントは、コードレビューを専門のサブエージェントに任せる。',
      },
      {
        en: 'invoke',
        pos: '動詞',
        ja: '呼び出して実行する',
        example: "The model decides when to invoke a tool based on the user's request.",
        exampleJa: 'モデルは、ユーザーの依頼に応じて、いつツールを呼び出すかを判断する。',
      },
      {
        en: 'retrieve',
        pos: '動詞',
        ja: '探して取り出す',
        example: 'The agent retrieves relevant documents before drafting an answer.',
        exampleJa: 'エージェントは、回答を書く前に関連する文書を探して取り出す。',
      },
      {
        en: 'iterate',
        pos: '動詞',
        ja: '繰り返し改善する',
        example: 'Iterate on the prompt based on the evaluation results.',
        exampleJa: '評価の結果をもとに、プロンプトを繰り返し改善する。',
      },
      {
        en: 'autonomous',
        pos: '形容詞',
        ja: '自律的な',
        example: 'Autonomous agents need clear limits on the actions they can take.',
        exampleJa: '自律的に動くエージェントには、取ってよい行動の範囲をはっきり決めておく必要がある。',
      },
      {
        en: 'idempotent',
        pos: '形容詞',
        ja: '何度実行しても影響が一度分と変わらない',
        note: '再試行しても二重に処理されない、という意味で使います。',
        example: 'Make the tool idempotent so that retries do not create duplicate orders.',
        exampleJa: '再試行しても注文が重複しないよう、ツールを何度実行しても結果が変わらない作りにする。',
        avoid: ['deterministic'],
      },
      {
        en: 'granular',
        pos: '形容詞',
        ja: 'きめ細かい',
        example: 'Granular permissions let administrators allow only specific commands.',
        exampleJa: 'きめ細かい権限設定により、管理者は特定のコマンドだけを許可できる。',
      },
      {
        en: 'human-in-the-loop',
        pos: '名詞',
        ja: '人が途中で確認や判断に加わる仕組み',
        example: 'Add a human-in-the-loop step before the agent sends emails to customers.',
        exampleJa: 'エージェントが顧客にメールを送る前に、人が確認する段階を設ける。',
      },
      {
        en: 'handoff',
        pos: '名詞',
        ja: '引き継ぎ',
        example: 'Design a clear handoff from the agent to a human support representative.',
        exampleJa: 'エージェントから人の担当者への引き継ぎを、はっきり設計しておく。',
      },
      {
        en: 'fallback',
        pos: '名詞',
        ja: 'うまくいかないときの代わりの手段',
        example: 'If the tool call fails, the agent should use a fallback instead of guessing.',
        exampleJa: 'ツールの呼び出しが失敗したら、エージェントは推測で答えず、代わりの手段を使うべきだ。',
      },
      {
        en: 'sandbox',
        pos: '名詞',
        ja: '隔離された実行環境',
        example: 'Run untrusted code in a sandbox.',
        exampleJa: '信頼できないコードは、隔離された環境で実行する。',
      },
      {
        en: 'least privilege',
        pos: '名詞',
        ja: '必要最小限の権限だけを与える原則',
        example: 'Following the principle of least privilege, give the agent read-only access.',
        exampleJa: '最小権限の原則に従い、エージェントには読み取り専用の権限を与える。',
      },
      {
        en: 'hook',
        pos: '名詞',
        ja: '決まった時点で処理を差し込む仕組み',
        example: 'A hook can run a formatter every time a file is edited.',
        exampleJa: 'フックを使うと、ファイルが編集されるたびに整形ツールを実行できる。',
      },
      {
        en: 'grounding',
        pos: '名詞',
        ja: '根拠となる情報に基づかせること',
        example: 'Grounding answers in retrieved documents helps reduce hallucinations.',
        exampleJa: '取り出した文書を根拠に回答させると、もっともらしい誤りを減らしやすくなる。',
      },
      {
        en: 'scope',
        pos: '名詞',
        ja: '（対象とする）範囲',
        example: "Limit the scope of the agent's task to a single repository.",
        exampleJa: 'エージェントの作業の範囲を、1 つのリポジトリに限る。',
      },
    ],
  },
  {
    id: 'safety',
    name: '安全性と評価',
    words: [
      {
        en: 'hallucination',
        pos: '名詞',
        ja: 'もっともらしい誤った出力',
        example: 'Asking the model to quote its sources can help reduce hallucinations.',
        exampleJa: '出典を引用するようモデルに求めると、もっともらしい誤りを減らしやすくなる。',
      },
      {
        en: 'prompt injection',
        pos: '名詞',
        ja: '外部の文章に指示を紛れ込ませる攻撃',
        example: 'A web page with hidden instructions is a common vector for prompt injection.',
        exampleJa: '隠れた指示を含む Web ページは、プロンプトインジェクションのよくある入り口だ。',
      },
      {
        en: 'jailbreak',
        pos: '名詞',
        ja: '安全上の制限を回避させようとする試み',
        example: 'Asking the model to role-play is a common jailbreak technique.',
        exampleJa: 'モデルにロールプレイをさせるのは、よくあるジェイルブレイクの手口だ。',
      },
      {
        en: 'guardrail',
        pos: '名詞',
        ja: '望ましくない動作を防ぐ仕組み',
        example: 'Add guardrails that block requests for personal data.',
        exampleJa: '個人データを求める依頼を止める仕組みを加える。',
      },
      {
        en: 'red teaming',
        pos: '名詞',
        ja: '攻撃者の立場で弱点を探す試験',
        example: 'Red teaming revealed that the agent could be tricked into leaking data.',
        exampleJa: 'レッドチーミングによって、エージェントがだまされてデータを漏らしうることが分かった。',
      },
      {
        en: 'misuse',
        pos: '名詞',
        ja: '悪用',
        example: 'The usage policy prohibits misuse such as creating malware.',
        exampleJa: '利用規約は、マルウェアの作成などの悪用を禁じている。',
      },
      {
        en: 'refusal',
        pos: '名詞',
        ja: '依頼を断ること',
        example: 'Overly cautious refusals frustrate legitimate users.',
        exampleJa: '必要以上に慎重な断りは、正当な利用者を困らせる。',
      },
      {
        en: 'rubric',
        pos: '名詞',
        ja: '採点の基準表',
        example: 'Write a rubric so that graders score responses consistently.',
        exampleJa: '採点者が一貫して評価できるよう、採点の基準表を作る。',
      },
      {
        en: 'baseline',
        pos: '名詞',
        ja: '比較のもとにする現状の値',
        example: 'Measure a baseline before you change the prompt.',
        exampleJa: 'プロンプトを変える前に、比較のもとにする現状の値を測っておく。',
      },
      {
        en: 'regression',
        pos: '名詞',
        ja: '以前できていたことができなくなること',
        note: '統計では「回帰」ですが、テストの文脈では、変更によって品質が後退することを指します。',
        example: 'Run the evaluation suite after each prompt change to catch regressions.',
        exampleJa: 'プロンプトを変えるたびに評価一式を実行し、品質の後退を見つける。',
      },
      {
        en: 'ground truth',
        pos: '名詞',
        ja: '正解として扱うデータ',
        example: "Compare the model's answers with ground truth labels.",
        exampleJa: 'モデルの回答を、正解ラベルと比べる。',
      },
      {
        en: 'edge case',
        pos: '名詞',
        ja: 'まれで境界的な場合',
        example: 'Include edge cases, such as empty inputs, in the test set.',
        exampleJa: '空の入力のような、まれで境界的な場合もテストセットに含める。',
      },
      {
        en: 'bias',
        pos: '名詞',
        ja: '偏り',
        example: 'Check whether the outputs show bias against any group of users.',
        exampleJa: '出力が、特定の利用者の集団に対して偏っていないかを確かめる。',
      },
      {
        en: 'adversarial',
        pos: '形容詞',
        ja: '敵対的な（悪意をもって仕掛ける）',
        example: 'Test the system with adversarial inputs before launch.',
        exampleJa: '公開前に、悪意を想定した入力でシステムを試験する。',
      },
      {
        en: 'redact',
        pos: '動詞',
        ja: '（機密部分を）伏せる',
        example: 'Redact personal information before sending documents to the model.',
        exampleJa: '文書をモデルに送る前に、個人情報を伏せる。',
      },
      {
        en: 'verify',
        pos: '動詞',
        ja: '正しいかを確かめる',
        example: 'Always verify generated code before deploying it.',
        exampleJa: '生成されたコードは、デプロイする前に必ず正しいかを確かめる。',
        avoid: ['ensure'],
      },
    ],
  },
  {
    id: 'ops',
    name: '導入と運用',
    words: [
      {
        en: 'governance',
        pos: '名詞',
        ja: '組織としての管理・統制',
        example: 'Enterprises need governance over which teams can use which models.',
        exampleJa: '企業には、どのチームがどのモデルを使えるかを管理する仕組みが必要だ。',
      },
      {
        en: 'compliance',
        pos: '名詞',
        ja: '法令や規程を守ること',
        example: 'The bank has strict compliance requirements for customer data.',
        exampleJa: 'その銀行には、顧客データについて、法令や規程の順守に関する厳しい要件がある。',
      },
      {
        en: 'audit log',
        pos: '名詞',
        ja: '誰がいつ何をしたかの記録',
        example: 'Administrators can review audit logs to see who changed the settings.',
        exampleJa: '管理者は監査ログを見て、誰が設定を変えたかを確認できる。',
      },
      {
        en: 'retention',
        pos: '名詞',
        ja: '（データを）保持すること',
        note: 'data retention policy（データの保持方針）の形でよく出てきます。',
        example: 'Confirm the data retention policy before uploading customer files.',
        exampleJa: '顧客のファイルをアップロードする前に、データの保持方針を確認する。',
      },
      {
        en: 'PII',
        pos: '名詞',
        ja: '個人を特定できる情報',
        note: 'personally identifiable information の略です。',
        example: 'Mask PII such as names and phone numbers in the logs.',
        exampleJa: 'ログに含まれる氏名や電話番号などの個人情報を隠す。',
      },
      {
        en: 'data residency',
        pos: '名詞',
        ja: 'データを保管する地域に関する要件',
        example: 'Some customers require data residency within their own country.',
        exampleJa: '顧客によっては、データを自国内に保管することを求める。',
      },
      {
        en: 'rollout',
        pos: '名詞',
        ja: '段階的な展開',
        example: 'Start the rollout with one department before expanding company-wide.',
        exampleJa: '全社に広げる前に、まず 1 つの部署から展開を始める。',
      },
      {
        en: 'rollback',
        pos: '名詞',
        ja: '以前の状態に戻すこと',
        example: 'Prepare a rollback plan in case the new prompt performs worse.',
        exampleJa: '新しいプロンプトの成績が悪かった場合に備えて、元に戻す計画を用意する。',
      },
      {
        en: 'pilot',
        pos: '名詞',
        ja: '小規模な試験導入',
        example: 'Run a pilot with a small group of users to collect feedback.',
        exampleJa: '少人数の利用者で試験導入を行い、意見を集める。',
      },
      {
        en: 'adoption',
        pos: '名詞',
        ja: '（組織への）定着・普及',
        example: 'Hands-on training can accelerate adoption across the organization.',
        exampleJa: '実習形式の研修は、組織全体への定着を早める。',
      },
      {
        en: 'observability',
        pos: '名詞',
        ja: 'システムの状態を外から把握できること',
        example: 'Good observability makes it easier to debug agent failures.',
        exampleJa: 'システムの状態を把握しやすくしておくと、エージェントの失敗を調べやすくなる。',
      },
      {
        en: 'use case',
        pos: '名詞',
        ja: '利用場面',
        example: 'Identify the use cases where Claude can deliver the most value.',
        exampleJa: 'Claude が最も価値を発揮できる利用場面を見極める。',
      },
      {
        en: 'provision',
        pos: '動詞',
        ja: '（利用環境を）用意して割り当てる',
        example: 'IT provisions user accounts automatically with SCIM.',
        exampleJa: 'IT 部門は、SCIM を使ってユーザーのアカウントを自動で用意する。',
      },
      {
        en: 'escalate',
        pos: '動詞',
        ja: '上位の担当者に引き上げる',
        example: 'Escalate the issue to a human when the agent is unsure.',
        exampleJa: 'エージェントが判断に迷うときは、人の担当者に対応を引き上げる。',
      },
      {
        en: 'scalable',
        pos: '形容詞',
        ja: '規模の拡大に対応できる',
        example: 'The architecture must be scalable to thousands of concurrent users.',
        exampleJa: 'その設計は、同時に数千人が使う規模にも対応できなければならない。',
      },
      {
        en: 'cost-effective',
        pos: '形容詞',
        ja: '費用対効果が高い',
        example: 'Smaller models are often more cost-effective for simple classification tasks.',
        exampleJa: '単純な分類の作業には、小さなモデルのほうが費用対効果が高いことが多い。',
      },
    ],
  },
];
